apiVersion: v1
kind: ServiceAccount
metadata:
  name: z21-can-manager
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: z21-detector-cr-reader
  namespace: default
rules:
  - apiGroups: ["zack.trains.io"]
    resources: ["detectors"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: z21-detector-cr-writer
  namespace: default
rules:
  - apiGroups: ["zack.trains.io"]
    resources: ["detectors"]
    verbs: ["create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: z21-detector-cr-status-writer
  namespace: default
rules:
  - apiGroups: ["zack.trains.io"]
    resources: ["detectors/status"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: z21-can-manager-reader
  namespace: default
subjects:
  - kind: ServiceAccount
    name: z21-can-manager
    namespace: default
roleRef:
  kind: Role
  name: z21-detector-cr-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: z21-can-manager-writer
  namespace: default
subjects:
  - kind: ServiceAccount
    name: z21-can-manager
    namespace: default
roleRef:
  kind: Role
  name: z21-detector-cr-writer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: z21-can-manager-updater
  namespace: default
subjects:
  - kind: ServiceAccount
    name: z21-can-manager
    namespace: default
roleRef:
  kind: Role
  name: z21-detector-cr-status-writer
  apiGroup: rbac.authorization.k8s.io
